### ISSUE TITLE
Improve the current SLI format

### ISSUE THREAD

**Issue by j-poecher** [keptn-contrib/dynatrace-service#625]
## Is your feature request related to a problem? Please describe the problem.

Currently when defining SLIs in the `sli.yaml` file, we are using a string format, that resembles a **not** encoded URL query string with possible extra prefixes and instructions for unit conversions.

Consider this `sli.yaml` as an example:

```{yaml}
---
spec_version: '1.0'
indicators:  
  response_time_p95: "MV2;MicroSecond;metricSelector=builtin:service.response.time:merge(\"dt.entity.service\"):percentile(95)&entitySelector=type(SERVICE),tag(keptn_managed),tag(keptn_service:$SERVICE)"
```

#### Issues with the current design:

* If the metrics query get more advanced and more complicated, this can lead to encoding problems as mentioned in e.g. #537 and parsing correctly might not be possible as mentioned in #571.
* *dynatrace-service* is not transparent on what extra processing is being done to the custom user defined metrics.

#### Goals / Requirements

1. Do not use *magic strings* for encoding SLIs, but use a more structured approach that simplifies mapping and extensibility
1. Be as transparent as possible for the end user from a Dynatrace API perspective. I.e. do not do any transformations or string manipulation on the parameters that would be needed by the API.
1. Be as extensive and open as possible. I.e. adding new API endpoints or adding/changing parameters for an existing endpoint should not be a problem.
1. We want to support additional properties per SLI that can be consumed by Keptn Lighthouse service:
   * `unit` - the unit that SLI value relates to and
   * `tags` - a list of strings that can be added. 
1. We want to support an additional *global* `tags` property that will be used for all SLIs.
1. All existing queries in the current format should be convertible to the new format - given the current restrictions on parsability.

#### Steps forward:

- [ ] Create a specification for the new SLI format
- [ ] Enable support for multiple SLI files in order to partition SLIs per domain, user group, etc.
- [ ] Discuss supporting multi-dimensional SLIs in files - which would also affect Keptn SLO specification and evaluation.

## Describe alternatives you've considered
There are no alternatives to changing the status-quo based on *magic strings*.

**Comment by j-poecher** [comment]
Please also see the discussion #626

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
